version: '3.9'

services:
  mobashi-main-ui:
    image: mobashi-main-ui
    container_name: mobashi-main-ui
    build:
      context: .
      dockerfile: ./Dockerfile
      target: production
      args:
        # Update 'VARIANT' to pick a Node version
        # Append -bullseye to pin to an OS version.
        # Use -bullseye variants on local on arm64/Apple Silicon.
        VARIANT: "20-bullseye"
        NPM_VERSION: "10.2.1"
        IONIC_CLI_VERSION: "7.1.1"
        IONIC_ANGULAR_VERSION: "7.5.1"
        BASE_HREF: "/ui/"
    #    ports:
    #      - 4001:4001
    volumes:
      - type: bind
        source: ./local_vars/production/configs
        target: /app/src/app/local_configs
        bind:
          create_host_path: true
        read_only: true
      - type: bind
        source: ./local_vars/production/assets
        target: /app/src/assets/local_assets
        bind:
          create_host_path: true
        read_only: true
